const content = {
  en: {
    nav: {
      profile: "Profile",
      principles: "Principles",
      tools: "Tools",
      lab: "Lesson Lab",
      qa: "Q&A",
      contact: "Contact",
      studio: "Back to NA Studio",
    },
    hero: {
      eyebrow: "NA Classroom / Teaching Portfolio",
      title: "Clarity first.\nConfidence follows.",
      subtitle: "A focused teaching portfolio by Nathan Azoulay ÔÇö built around clear explanations, patient feedback, mathematics, FLE, and useful learning tools.",
      humanLine: "The best tool in the classroom is still attention.",
      cta1: "Enter the classroom",
      cta2: "See the method",
      annotations: ["why?", "almost", "try again", "clearer"],
    },
    desk: {
      title: "The teacher's desk",
      tagline: "Not technology instead of teaching. Technology after attention.",
      sheets: {
        profile: {
          label: "Profile",
          items: [
            { title: "Mathematics", detail: "Tutoring experience from fundamentals to exam-oriented reasoning." },
            { title: "Statistics", detail: "Comfortable explaining formulas through intuition, examples and interpretation." },
            { title: "Business Analytics", detail: "Academic path connecting quantitative reasoning, business context and decision-making." },
            { title: "Data analysis", detail: "Practical orientation toward cleaning, reporting, dashboards and operational insights." },
            { title: "Data science foundations", detail: "Enough ML culture to explain data logic without making it a technical showcase." },
            { title: "AI & digital culture", detail: "Uses digital tools as support for clarity and practice ÔÇö never as a replacement for teaching." },
            { title: "Clear explanation", detail: "Focuses on making complex ideas usable, not impressive." },
          ],
        },
        experience: {
          label: "Experience",
          items: [
            { title: "Teaching & tutoring", detail: "Experience supporting learners through mathematics, methodology and academic progression." },
            { title: "Academic support", detail: "Helps students rebuild structure when a course feels fragmented or overwhelming." },
            { title: "Mathematics support", detail: "Works on both method and meaning: not only how to solve, but why the method works." },
            { title: "Statistics / quantitative reasoning", detail: "Connects calculations to interpretation ÔÇö where many students lose confidence." },
            { title: "Methodology coaching", detail: "Helps learners organize revision, identify weak points and stop repeating mistakes." },
            { title: "Foreign learners", detail: "Experience helping non-native learners cross language and confidence barriers." },
            { title: "FLE / French as a Foreign Language", detail: "Supports French learning through patterns, examples, repetition and low-pressure correction." },
          ],
        },
        languages: {
          label: "Languages",
          items: [
            { title: "French ÔÇö native", detail: "Native language, useful for precise explanation and FLE support." },
            { title: "English ÔÇö B2 / professional", detail: "Comfortable enough to explain, exchange and support learners across languages." },
            { title: "Spanish ÔÇö B1 / conversational", detail: "Useful for basic explanation bridges and multilingual learner contexts." },
          ],
          note: "Languages are not decoration here. They help Nathan explain the same idea through different cultural and linguistic entry points.",
        },
      },
    },
    board: {
      title: "What good teaching starts with",
      signature: "Teach the mistake, not just the lesson.",
      flow: "confusion ÔåÆ diagnosis ÔåÆ explanation ÔåÆ exercise ÔåÆ confidence",
      principles: [
        { num: "01", name: "Attention before explanation", note: "First observe: what is missing, what is confused, what is fragile." },
        { num: "02", name: "Clarity before speed", note: "Moving fast is useless if the learner is only copying steps." },
        { num: "03", name: "Feedback that can be used", note: "Correction shows what to do next, not only what went wrong." },
        { num: "04", name: "Confidence through structure", note: "Confidence grows when the learner sees a path, not a wall." },
        { num: "05", name: "Tools only when useful", note: "Digital tools support the lesson. They never replace the relationship." },
      ],
    },
    tools: {
      title: "Tools on the table",
      intro: "Digital tools are useful only when they help a teacher see better, explain better, or help a learner practice with less fear.",
      label: "Concepts / prototypes / educational explorations",
      statusLabel: "Status",
      githubLabel: "GitHub coming soon",
      closeLabel: "Close",
      apps: [
        {
          id: "formula-builder",
          name: "Formula Builder",
          short: "Understand formulas instead of memorizing them.",
          description: "Formula Builder deconstructs scientific and quantitative formulas step by step. The learner manipulates each part of the formula and sees what changes.",
          value: "Students often learn formulas like recipes. This tool helps them understand what each part means.",
          targets: ["Middle school", "High school", "Early university", "Statistics / data / finance beginners"],
          features: ["20 core formulas", "Interactive visualizations", "Mini exercises per formula", "Concrete real-world cases", "Teacher mode for custom sheets"],
          examples: ["Mean", "Percentage", "Speed = distance / time", "Probability", "Variance / std deviation", "Affine function", "Excel formulas"],
          status: "Concept",
          githubUrl: null,
        },
        {
          id: "error-diary",
          name: "Error Diary",
          short: "Turn recurring mistakes into targeted practice.",
          description: "A smart journal where the teacher records recurring mistakes and transforms them into exercises, patterns and structured feedback.",
          value: "Turns mistakes into usable feedback instead of repeated corrections.",
          targets: ["Any level", "High-stakes exam prep", "Learners stuck on the same errors"],
          features: ["Mistake categories", "Recurring pattern detection", "Exercise suggestions", "Student progress notes", "Teacher summary view"],
          examples: [],
          status: "Concept",
          githubUrl: null,
        },
        {
          id: "oralsafe",
          name: "OralSafe",
          short: "Practice speaking before feeling perfect.",
          description: "A low-pressure oral practice tool for shy learners and FLE learners. Built around short voice prompts, repetition and progressive confidence.",
          value: "Helps learners speak before they feel ready ÔÇö which is when real acquisition begins.",
          targets: ["FLE learners", "Shy or anxious speakers", "B1-B2 oral prep"],
          features: ["Short voice prompts", "Repetition loops", "Confidence level tracking", "Pronunciation notes", "Teacher feedback mode"],
          examples: [],
          status: "Concept",
          githubUrl: null,
        },
        {
          id: "microexam",
          name: "MicroExam",
          short: "Check understanding in ten minutes.",
          description: "A mini-assessment generator for quick concept checks before moving forward. Reveals gaps early ÔÇö not at the final exam.",
          value: "Most learners pass the lesson but fail the concept. MicroExam catches the gap.",
          targets: ["Any subject", "Before moving to a new chapter", "Revision sessions"],
          features: ["Topic selection", "10-minute test mode", "Auto-correction structure", "Teacher notes", "Revision suggestions"],
          examples: [],
          status: "Concept",
          githubUrl: null,
        },
        {
          id: "concept-builder",
          name: "Concept Builder",
          short: "Explain the same idea in several ways.",
          description: "A tool that helps teachers explain one concept through different modes: simple, visual, analogy-based, exam-focused or step-by-step.",
          value: "Every learner has a different entry point. Concept Builder finds theirs.",
          targets: ["Any teacher", "Learners who need alternative explanations", "Tutoring sessions"],
          features: ["Concept input", "Multiple explanation levels", "Analogy mode", "Exercise mode", "Teacher export"],
          examples: [],
          status: "Concept",
          githubUrl: null,
        },
        {
          id: "learning-map",
          name: "Learning Map",
          short: "See what is solid, fragile or missing.",
          description: "A visual map of learning progression. The teacher and learner see exactly what is mastered, what needs review, and what is blocking progress.",
          value: "Makes invisible gaps visible ÔÇö before they become failures.",
          targets: ["Long-term tutoring", "Exam prep", "Teachers with multiple students"],
          features: ["Mastered / fragile / missing states", "Concept dependencies", "Progress path visualization", "Revision priorities", "Teacher & student views"],
          examples: [],
          status: "Concept",
          githubUrl: null,
        },
      ],
    },
    lab: {
      title: "Two lessons, two ways",
      subtitle: "The same teaching attention, applied to two very different learner problems.",
      quote: "Human first. Method next. Digital in support.",
      math: {
        tag: "Mathematics",
        problem: "Mean vs Median",
        learnerSays: "I know the formula, but I don't know when to use it.",
        diagnosis: "The learner memorized the operation, not the meaning.",
        explanation: "Mean is balance. Median is position.",
        exercise: "Create two datasets with the same mean but different medians.",
        feedback: "Which measure represents the group better ÔÇö and why?",
      },
      fle: {
        tag: "FLE / French",
        problem: "Un vs Une",
        learnerSays: "I always mix them up.",
        diagnosis: "Gender is not yet seen as a system ÔÇö only as random rules.",
        explanation: "We group words by endings, sounds and repeated patterns ÔÇö not by memorization.",
        exercise: "Sort 20 common nouns. Then explain the pattern you noticed.",
        feedback: "What helped you guess correctly?",
      },
      steps: ["Learner says", "Diagnosis", "Explanation", "Exercise", "Feedback"],
    },
    qa: {
      title: "Questions a recruiter might ask",
      items: [
        {
          q: "What kind of position are you looking for?",
          a: "I am open to a real teaching position, tutoring, academic support, FLE, training, or education-adjacent roles where clarity, structure and adaptation matter.",
        },
        {
          q: "Is this only about tutoring?",
          a: "No. Tutoring is part of my experience, but the goal is broader: teaching, helping learners progress, and contributing to educational environments where explanation and structure matter.",
        },
        {
          q: "Is this mainly about apps?",
          a: "No. The human lesson comes first. Apps are only useful when they help diagnose, practice, explain or follow progress better.",
        },
        {
          q: "What subjects can you teach or support?",
          a: "Mathematics, statistics, quantitative reasoning, data analysis foundations, business analytics logic, methodology, and French as a Foreign Language.",
        },
        {
          q: "What makes your profile different?",
          a: "I combine teaching experience, analytical thinking, data culture, multilingual communication and the ability to design simple learning tools.",
        },
        {
          q: "Are you available for interviews?",
          a: "Yes. The best next step is a direct conversation.",
        },
      ],
    },
    cta: {
      title: "Enter the classroom",
      body: "If you are looking for someone who can teach clearly, adapt to learners, and bring structure into learning, I would be happy to talk.",
      button: "Contact Nathan",
      secondary: "Back to NA Studio",
      email: "contact@nathanazoulay.com",
    },
    footer: {
      line: "NA Classroom ÔÇö a focused teaching room by Nathan Azoulay / NA Studio.",
      links: [
        { label: "NA Studio", href: "/" },
        { label: "NA Websites", href: "/" },
        { label: "Contact", href: "mailto:contact@nathanazoulay.com" },
        { label: "LinkedIn", href: "https://linkedin.com" },
      ],
    },
  },

  fr: {
    nav: {
      profile: "Profil",
      principles: "Principes",
      tools: "Outils",
      lab: "Labo",
      qa: "Q&R",
      contact: "Contact",
      studio: "Retour à NA Studio",
    },
    hero: {
      eyebrow: "NA Classroom / Portfolio p├®dagogique",
      title: "La clart├® d'abord.\nLa confiance suit.",
      subtitle: "Un portfolio p├®dagogique cibl├® par Nathan Azoulay ÔÇö autour d'explications claires, de feedback patient, de math├®matiques, de FLE et d'outils d'apprentissage utiles.",
      humanLine: "Le meilleur outil dans une salle de classe reste l'attention.",
      cta1: "Entrer dans la classe",
      cta2: "Voir la m├®thode",
      annotations: ["pourquoi ?", "presque", "r├®essaie", "plus clair"],
    },
    desk: {
      title: "Le bureau p├®dagogique",
      tagline: "Pas la technologie ├á la place de l'enseignement. La technologie apr├¿s l'attention.",
      sheets: {
        profile: {
          label: "Profil",
          items: [
            { title: "Math├®matiques", detail: "Exp├®rience de tutorat des fondamentaux au raisonnement orient├® examen." },
            { title: "Statistiques", detail: "├Ç l'aise pour expliquer les formules par l'intuition, les exemples et l'interpr├®tation." },
            { title: "Business Analytics", detail: "Parcours acad├®mique reliant raisonnement quantitatif, contexte m├®tier et prise de d├®cision." },
            { title: "Analyse de donn├®es", detail: "Orientation pratique vers le nettoyage, le reporting, les tableaux de bord et les insights op├®rationnels." },
            { title: "Fondations data science", detail: "Culture ML suffisante pour expliquer la logique des donn├®es sans en faire une vitrine technique." },
            { title: "Culture IA & num├®rique", detail: "Utilise les outils num├®riques comme support pour la clart├® et la pratique ÔÇö jamais ├á la place de l'enseignement." },
            { title: "Explication claire", detail: "Se concentre sur rendre les id├®es complexes utilisables, pas impressionnantes." },
          ],
        },
        experience: {
          label: "Exp├®rience",
          items: [
            { title: "Enseignement et tutorat", detail: "Exp├®rience d'accompagnement en math├®matiques, m├®thodologie et progression acad├®mique." },
            { title: "Soutien scolaire", detail: "Aide les ├®l├¿ves ├á reconstruire la structure quand un cours semble fragment├® ou ├®crasant." },
            { title: "Soutien en math├®matiques", detail: "Travaille sur m├®thode et sens : pas seulement comment r├®soudre, mais pourquoi la m├®thode fonctionne." },
            { title: "Statistiques / raisonnement quantitatif", detail: "Relie les calculs ├á l'interpr├®tation ÔÇö l├á o├╣ beaucoup d'├®tudiants perdent confiance." },
            { title: "Coaching m├®thodologique", detail: "Aide les apprenants ├á organiser la r├®vision, identifier les points faibles et cesser de r├®p├®ter les erreurs." },
            { title: "Apprenants ├®trangers", detail: "Exp├®rience pour aider les non-natifs ├á franchir les barri├¿res linguistiques et de confiance." },
            { title: "FLE / Fran├ºais Langue ├ëtrang├¿re", detail: "Soutient l'apprentissage du fran├ºais par les sch├®mas, exemples, r├®p├®tition et correction basse pression." },
          ],
        },
        languages: {
          label: "Langues",
          items: [
            { title: "Fran├ºais ÔÇö natif", detail: "Langue maternelle, utile pour une explication pr├®cise et le soutien FLE." },
            { title: "Anglais ÔÇö B2 / professionnel", detail: "Assez ├á l'aise pour expliquer, ├®changer et accompagner les apprenants entre les langues." },
            { title: "Espagnol ÔÇö B1 / conversationnel", detail: "Utile pour les ponts d'explication de base et les contextes d'apprenants multilingues." },
          ],
          note: "Les langues ne sont pas ici une d├®coration. Elles aident Nathan ├á expliquer la m├¬me id├®e ├á travers diff├®rents points d'entr├®e culturels et linguistiques.",
        },
      },
    },
    board: {
      title: "Ce par quoi commence un bon enseignement",
      signature: "Enseigner l'erreur, pas seulement la le├ºon.",
      flow: "confusion ÔåÆ diagnostic ÔåÆ explication ÔåÆ exercice ÔåÆ confiance",
      principles: [
        { num: "01", name: "L'attention avant l'explication", note: "Observer d'abord : ce qui manque, ce qui est confus, ce qui est fragile." },
        { num: "02", name: "La clart├® avant la vitesse", note: "Aller vite ne sert ├á rien si l'├®l├¿ve ne fait que copier des ├®tapes." },
        { num: "03", name: "Un feedback utilisable", note: "La correction montre quoi faire ensuite, pas seulement ce qui est faux." },
        { num: "04", name: "La confiance par la structure", note: "La confiance grandit quand l'├®l├¿ve voit un chemin, pas un mur." },
        { num: "05", name: "Les outils seulement quand utiles", note: "Les outils num├®riques soutiennent le cours. Ils ne remplacent jamais la relation." },
      ],
    },
    tools: {
      title: "Des outils sur la table",
      intro: "Les outils num├®riques sont utiles seulement quand ils aident un enseignant ├á mieux voir, mieux expliquer, ou un apprenant ├á pratiquer avec moins de peur.",
      label: "Concepts / prototypes / explorations p├®dagogiques",
      statusLabel: "Statut",
      githubLabel: "GitHub bient├┤t",
      closeLabel: "Fermer",
      apps: [
        {
          id: "formula-builder",
          name: "Formula Builder",
          short: "Comprendre les formules au lieu de les m├®moriser.",
          description: "Formula Builder d├®construit les formules scientifiques et quantitatives ├®tape par ├®tape. L'apprenant manipule chaque partie et voit ce qui change.",
          value: "Les ├®l├¿ves apprennent souvent les formules comme des recettes. Cet outil les aide ├á comprendre ce que chaque partie signifie.",
          targets: ["Coll├¿ge", "Lyc├®e", "D├®but universitaire", "D├®butants en stats / data / finance"],
          features: ["20 formules essentielles", "Visualisations interactives", "Mini exercices par formule", "Cas concrets", "Mode enseignant"],
          examples: ["Moyenne", "Pourcentage", "Vitesse = distance / temps", "Probabilit├®", "Variance / ├®cart-type", "Fonction affine", "Formules Excel"],
          status: "Concept",
          githubUrl: null,
        },
        {
          id: "error-diary",
          name: "Error Diary",
          short: "Transformer les erreurs r├®currentes en exercices cibl├®s.",
          description: "Un journal intelligent o├╣ l'enseignant consigne les erreurs r├®currentes et les transforme en exercices, sch├®mas et feedback structur├®.",
          value: "Transforme les erreurs en feedback utilisable plut├┤t qu'en corrections r├®p├®t├®es.",
          targets: ["Tous niveaux", "Pr├®paration aux examens", "Apprenants bloqu├®s sur les m├¬mes erreurs"],
          features: ["Cat├®gories d'erreurs", "D├®tection de sch├®mas r├®currents", "Suggestions d'exercices", "Notes de progression", "Vue synth├®tique enseignant"],
          examples: [],
          status: "Concept",
          githubUrl: null,
        },
        {
          id: "oralsafe",
          name: "OralSafe",
          short: "Pratiquer l'oral avant de se sentir parfait.",
          description: "Un outil de pratique orale basse pression pour les apprenants timides et les apprenants en FLE. Bas├® sur des prompts courts, la r├®p├®tition et la confiance progressive.",
          value: "Aide les apprenants ├á parler avant de se sentir pr├¬ts ÔÇö moment o├╣ commence vraiment l'acquisition.",
          targets: ["Apprenants FLE", "Locuteurs timides ou anxieux", "Pr├®paration orale B1-B2"],
          features: ["Prompts vocaux courts", "Boucles de r├®p├®tition", "Suivi du niveau de confiance", "Notes de prononciation", "Mode feedback enseignant"],
          examples: [],
          status: "Concept",
          githubUrl: null,
        },
        {
          id: "microexam",
          name: "MicroExam",
          short: "V├®rifier la compr├®hension en dix minutes.",
          description: "Un g├®n├®rateur de mini-├®valuations pour v├®rifier rapidement qu'un concept est compris avant d'avancer.",
          value: "La plupart des apprenants passent la le├ºon mais ratent le concept. MicroExam comble cet ├®cart.",
          targets: ["Toute mati├¿re", "Avant de passer au chapitre suivant", "Sessions de r├®vision"],
          features: ["S├®lection de th├¿me", "Mode test 10 minutes", "Structure de correction automatique", "Notes enseignant", "Suggestions de r├®vision"],
          examples: [],
          status: "Concept",
          githubUrl: null,
        },
        {
          id: "concept-builder",
          name: "Concept Builder",
          short: "Expliquer la m├¬me id├®e de plusieurs fa├ºons.",
          description: "Un outil qui aide les enseignants ├á expliquer un concept selon diff├®rents modes : simple, visuel, par analogie, orient├® examen ou ├®tape par ├®tape.",
          value: "Chaque apprenant a un point d'entr├®e diff├®rent. Concept Builder le trouve.",
          targets: ["Tout enseignant", "Apprenants n├®cessitant des explications alternatives", "Sessions de tutorat"],
          features: ["Saisie du concept", "Plusieurs niveaux d'explication", "Mode analogie", "Mode exercice", "Export enseignant"],
          examples: [],
          status: "Concept",
          githubUrl: null,
        },
        {
          id: "learning-map",
          name: "Learning Map",
          short: "Voir ce qui est solide, fragile ou manquant.",
          description: "Une carte visuelle de la progression d'apprentissage. L'enseignant et l'apprenant voient pr├®cis├®ment ce qui est ma├«tris├®, ce qui doit ├¬tre revu et ce qui bloque.",
          value: "Rend les lacunes invisibles visibles ÔÇö avant qu'elles deviennent des ├®checs.",
          targets: ["Tutorat long terme", "Pr├®paration aux examens", "Enseignants avec plusieurs ├®l├¿ves"],
          features: ["├ëtats ma├«tris├® / fragile / manquant", "D├®pendances entre concepts", "Visualisation du chemin", "Priorit├®s de r├®vision", "Vues enseignant et ├®l├¿ve"],
          examples: [],
          status: "Concept",
          githubUrl: null,
        },
      ],
    },
    lab: {
      title: "Deux le├ºons, deux chemins",
      subtitle: "La m├¬me attention p├®dagogique, appliqu├®e ├á deux probl├¿mes d'apprentissage tr├¿s diff├®rents.",
      quote: "Humain d'abord. M├®thode ensuite. Digital en soutien.",
      math: {
        tag: "Math├®matiques",
        problem: "Moyenne vs M├®diane",
        learnerSays: "Je connais la formule, mais je ne sais pas quand l'utiliser.",
        diagnosis: "L'├®l├¿ve a m├®moris├® l'op├®ration, pas le sens.",
        explanation: "La moyenne, c'est l'├®quilibre. La m├®diane, c'est la position.",
        exercise: "Cr├®er deux jeux de donn├®es avec la m├¬me moyenne mais des m├®dianes diff├®rentes.",
        feedback: "Quelle mesure repr├®sente mieux le groupe ÔÇö et pourquoi ?",
      },
      fle: {
        tag: "FLE / Fran├ºais",
        problem: "Un vs Une",
        learnerSays: "Je les m├®lange toujours.",
        diagnosis: "Le genre n'est pas encore per├ºu comme un syst├¿me ÔÇö seulement comme des r├¿gles al├®atoires.",
        explanation: "On regroupe les mots par terminaisons, sons et sch├®mas r├®p├®t├®s ÔÇö pas par m├®morisation.",
        exercise: "Trier 20 noms courants. Puis expliquer le sch├®ma remarqu├®.",
        feedback: "Qu'est-ce qui vous a aid├® ├á deviner correctement ?",
      },
      steps: ["L'├®l├¿ve dit", "Diagnostic", "Explication", "Exercice", "Feedback"],
    },
    qa: {
      title: "Questions qu'un recruteur peut se poser",
      items: [
        { q: "Quel type de poste recherchez-vous ?", a: "Je suis ouvert ├á un vrai poste d'enseignant, au tutorat, au soutien scolaire, au FLE, ├á la formation ou ├á des r├┤les li├®s ├á l'├®ducation o├╣ la clart├®, la structure et l'adaptation comptent." },
        { q: "Est-ce seulement du tutorat ?", a: "Non. Le tutorat fait partie de mon exp├®rience, mais l'objectif est plus large : enseigner, aider les apprenants ├á progresser et contribuer ├á des environnements ├®ducatifs o├╣ l'explication et la structure comptent." },
        { q: "Est-ce principalement une question d'applications ?", a: "Non. La le├ºon humaine vient d'abord. Les applications ne sont utiles que si elles aident ├á diagnostiquer, pratiquer, expliquer ou suivre les progr├¿s." },
        { q: "Quelles mati├¿res pouvez-vous enseigner ou accompagner ?", a: "Math├®matiques, statistiques, raisonnement quantitatif, bases d'analyse de donn├®es, logique business analytics, m├®thodologie et Fran├ºais Langue ├ëtrang├¿re." },
        { q: "Qu'est-ce qui rend votre profil diff├®rent ?", a: "Je combine exp├®rience p├®dagogique, pens├®e analytique, culture data, communication multilingue et capacit├® ├á concevoir des outils d'apprentissage simples." },
        { q: "├ètes-vous disponible pour un entretien ?", a: "Oui. La meilleure prochaine ├®tape est une conversation directe." },
      ],
    },
    cta: {
      title: "Entrer dans la classe",
      body: "Si vous cherchez quelqu'un capable d'enseigner clairement, de s'adapter aux apprenants et d'apporter de la structure dans l'apprentissage, je serais heureux d'├®changer.",
      button: "Contacter Nathan",
      secondary: "Retour ├á NA Studio",
      email: "contact@nathanazoulay.com",
    },
    footer: {
      line: "NA Classroom ÔÇö un espace p├®dagogique d├®di├® par Nathan Azoulay / NA Studio.",
      links: [
        { label: "NA Studio", href: "/" },
        { label: "NA Websites", href: "/" },
        { label: "Contact", href: "mailto:contact@nathanazoulay.com" },
        { label: "LinkedIn", href: "https://linkedin.com" },
      ],
    },
  },

  es: {
    nav: {
      profile: "Perfil",
      principles: "Principios",
      tools: "Herramientas",
      lab: "Laboratorio",
      qa: "Preguntas",
      contact: "Contacto",
      studio: "Volver a NA Studio",
    },
    hero: {
      eyebrow: "NA Classroom / Portfolio pedag├│gico",
      title: "Primero claridad.\nLuego confianza.",
      subtitle: "Un portfolio pedag├│gico enfocado por Nathan Azoulay ÔÇö basado en explicaciones claras, feedback paciente, matem├íticas, FLE y herramientas de aprendizaje ├║tiles.",
      humanLine: "La mejor herramienta en el aula sigue siendo la atenci├│n.",
      cta1: "Entrar en el aula",
      cta2: "Ver el m├®todo",
      annotations: ["┬┐por qu├®?", "casi", "int├®ntalo", "m├ís claro"],
    },
    desk: {
      title: "El escritorio pedag├│gico",
      tagline: "No tecnolog├¡a en lugar de ense├▒anza. Tecnolog├¡a despu├®s de la atenci├│n.",
      sheets: {
        profile: {
          label: "Perfil",
          items: [
            { title: "Matem├íticas", detail: "Experiencia de tutor├¡a desde los fundamentos hasta el razonamiento orientado a ex├ímenes." },
            { title: "Estad├¡stica", detail: "C├│modo explicando f├│rmulas a trav├®s de la intuici├│n, ejemplos e interpretaci├│n." },
            { title: "Business Analytics", detail: "Trayectoria acad├®mica que conecta razonamiento cuantitativo, contexto empresarial y toma de decisiones." },
            { title: "An├ílisis de datos", detail: "Orientaci├│n pr├íctica hacia limpieza, reporting, dashboards e insights operacionales." },
            { title: "Fundamentos data science", detail: "Cultura ML suficiente para explicar la l├│gica de datos sin convertirlo en un escaparate t├®cnico." },
            { title: "Cultura IA & digital", detail: "Usa herramientas digitales como apoyo para la claridad y la pr├íctica ÔÇö nunca en lugar de la ense├▒anza." },
            { title: "Explicaci├│n clara", detail: "Se centra en hacer las ideas complejas utilizables, no impresionantes." },
          ],
        },
        experience: {
          label: "Experiencia",
          items: [
            { title: "Ense├▒anza y tutor├¡a", detail: "Experiencia apoyando alumnos en matem├íticas, metodolog├¡a y progresi├│n acad├®mica." },
            { title: "Apoyo acad├®mico", detail: "Ayuda a los alumnos a reconstruir la estructura cuando un curso se siente fragmentado o abrumador." },
            { title: "Apoyo en matem├íticas", detail: "Trabaja en m├®todo y significado: no solo c├│mo resolver, sino por qu├® funciona el m├®todo." },
            { title: "Estad├¡stica / razonamiento cuantitativo", detail: "Conecta c├ílculos con interpretaci├│n ÔÇö donde muchos alumnos pierden confianza." },
            { title: "Coaching metodol├│gico", detail: "Ayuda a los alumnos a organizar la revisi├│n, identificar puntos d├®biles y dejar de repetir errores." },
            { title: "Alumnos extranjeros", detail: "Experiencia ayudando a no nativos a cruzar barreras ling├╝├¡sticas y de confianza." },
            { title: "FLE / Franc├®s como Lengua Extranjera", detail: "Apoya el aprendizaje del franc├®s mediante patrones, ejemplos, repetici├│n y correcci├│n sin presi├│n." },
          ],
        },
        languages: {
          label: "Idiomas",
          items: [
            { title: "Franc├®s ÔÇö nativo", detail: "Lengua materna, ├║til para explicaci├│n precisa y apoyo FLE." },
            { title: "Ingl├®s ÔÇö B2 / profesional", detail: "Lo suficientemente c├│modo para explicar, intercambiar y apoyar alumnos entre idiomas." },
            { title: "Espa├▒ol ÔÇö B1 / conversacional", detail: "├Ütil para puentes b├ísicos de explicaci├│n y contextos de alumnos multiling├╝es." },
          ],
          note: "Los idiomas no son decoraci├│n aqu├¡. Ayudan a Nathan a explicar la misma idea a trav├®s de diferentes puntos de entrada culturales y ling├╝├¡sticos.",
        },
      },
    },
    board: {
      title: "Por d├│nde empieza una buena ense├▒anza",
      signature: "Ense├▒a el error, no solo la lecci├│n.",
      flow: "confusi├│n ÔåÆ diagn├│stico ÔåÆ explicaci├│n ÔåÆ ejercicio ÔåÆ confianza",
      principles: [
        { num: "01", name: "Atenci├│n antes que explicaci├│n", note: "Primero observar: qu├® falta, qu├® est├í confuso, qu├® es fr├ígil." },
        { num: "02", name: "Claridad antes que velocidad", note: "Ir r├ípido no sirve si el alumno solo copia pasos." },
        { num: "03", name: "Feedback que se pueda usar", note: "La correcci├│n muestra qu├® hacer despu├®s, no solo qu├® sali├│ mal." },
        { num: "04", name: "Confianza a trav├®s de la estructura", note: "La confianza crece cuando el alumno ve un camino, no un muro." },
        { num: "05", name: "Herramientas solo cuando son ├║tiles", note: "Las herramientas digitales apoyan la clase. Nunca reemplazan la relaci├│n." },
      ],
    },
    tools: {
      title: "Herramientas sobre la mesa",
      intro: "Las herramientas digitales solo son ├║tiles cuando ayudan al profesor a ver mejor, explicar mejor o al alumno a practicar con menos miedo.",
      label: "Conceptos / prototipos / exploraciones educativas",
      statusLabel: "Estado",
      githubLabel: "GitHub pr├│ximamente",
      closeLabel: "Cerrar",
      apps: [
        {
          id: "formula-builder",
          name: "Formula Builder",
          short: "Entender las f├│rmulas en lugar de memorizarlas.",
          description: "Formula Builder deconstruye f├│rmulas cient├¡ficas y cuantitativas paso a paso. El alumno manipula cada parte y ve qu├® cambia.",
          value: "Los alumnos suelen aprender f├│rmulas como recetas. Esta herramienta les ayuda a entender qu├® significa cada parte.",
          targets: ["Secundaria", "Bachillerato", "Inicio universitario", "Principiantes en estad├¡stica / datos / finanzas"],
          features: ["20 f├│rmulas esenciales", "Visualizaciones interactivas", "Mini ejercicios por f├│rmula", "Casos reales", "Modo profesor"],
          examples: ["Media", "Porcentaje", "Velocidad = distancia / tiempo", "Probabilidad", "Varianza / desviaci├│n est├índar", "Funci├│n af├¡n", "F├│rmulas Excel"],
          status: "Concepto",
          githubUrl: null,
        },
        {
          id: "error-diary",
          name: "Error Diary",
          short: "Convertir errores recurrentes en pr├íctica dirigida.",
          description: "Un diario inteligente donde el profesor registra errores recurrentes y los transforma en ejercicios, patrones y feedback estructurado.",
          value: "Convierte errores en feedback ├║til en lugar de correcciones repetidas.",
          targets: ["Cualquier nivel", "Preparaci├│n a ex├ímenes", "Alumnos atascados en los mismos errores"],
          features: ["Categor├¡as de errores", "Detecci├│n de patrones recurrentes", "Sugerencias de ejercicios", "Notas de progreso", "Vista resumen profesor"],
          examples: [],
          status: "Concepto",
          githubUrl: null,
        },
        {
          id: "oralsafe",
          name: "OralSafe",
          short: "Practicar el oral antes de sentirse perfecto.",
          description: "Una herramienta de pr├íctica oral sin presi├│n para alumnos t├¡midos y de FLE. Basada en prompts cortos, repetici├│n y confianza progresiva.",
          value: "Ayuda a los alumnos a hablar antes de sentirse listos ÔÇö cuando comienza la adquisici├│n real.",
          targets: ["Alumnos de FLE", "Hablantes t├¡midos o ansiosos", "Preparaci├│n oral B1-B2"],
          features: ["Prompts de voz cortos", "Bucles de repetici├│n", "Seguimiento del nivel de confianza", "Notas de pronunciaci├│n", "Modo feedback profesor"],
          examples: [],
          status: "Concepto",
          githubUrl: null,
        },
        {
          id: "microexam",
          name: "MicroExam",
          short: "Comprobar la comprensi├│n en diez minutos.",
          description: "Un generador de mini-evaluaciones para verificar r├ípidamente que un concepto se entendi├│ antes de avanzar.",
          value: "La mayor├¡a de alumnos pasan la clase pero fallan el concepto. MicroExam detecta ese hueco.",
          targets: ["Cualquier materia", "Antes de pasar al siguiente tema", "Sesiones de repaso"],
          features: ["Selecci├│n de tema", "Modo test 10 minutos", "Estructura de correcci├│n autom├ítica", "Notas del profesor", "Sugerencias de revisi├│n"],
          examples: [],
          status: "Concepto",
          githubUrl: null,
        },
        {
          id: "concept-builder",
          name: "Concept Builder",
          short: "Explicar la misma idea de varias maneras.",
          description: "Una herramienta que ayuda a los profesores a explicar un concepto mediante distintos modos: simple, visual, por analog├¡a, orientado a examen o paso a paso.",
          value: "Cada alumno tiene un punto de entrada diferente. Concept Builder lo encuentra.",
          targets: ["Cualquier profesor", "Alumnos que necesitan explicaciones alternativas", "Sesiones de tutor├¡a"],
          features: ["Entrada del concepto", "Varios niveles de explicaci├│n", "Modo analog├¡a", "Modo ejercicio", "Exportaci├│n para profesor"],
          examples: [],
          status: "Concepto",
          githubUrl: null,
        },
        {
          id: "learning-map",
          name: "Learning Map",
          short: "Ver lo que es s├│lido, fr├ígil o falta.",
          description: "Un mapa visual de la progresi├│n de aprendizaje. El profesor y el alumno ven exactamente qu├® est├í dominado, qu├® hay que revisar y qu├® bloquea el avance.",
          value: "Hace visibles las lagunas invisibles ÔÇö antes de que se conviertan en fracasos.",
          targets: ["Tutor├¡a a largo plazo", "Preparaci├│n a ex├ímenes", "Profesores con varios alumnos"],
          features: ["Estados dominado / fr├ígil / faltante", "Dependencias entre conceptos", "Visualizaci├│n del camino", "Prioridades de revisi├│n", "Vistas profesor y alumno"],
          examples: [],
          status: "Concepto",
          githubUrl: null,
        },
      ],
    },
    lab: {
      title: "Dos lecciones, dos caminos",
      subtitle: "La misma atenci├│n pedag├│gica, aplicada a dos problemas de aprendizaje muy distintos.",
      quote: "Humano primero. M├®todo despu├®s. Digital en apoyo.",
      math: {
        tag: "Matem├íticas",
        problem: "Media vs Mediana",
        learnerSays: "Conozco la f├│rmula, pero no s├® cu├índo usarla.",
        diagnosis: "El alumno memoriz├│ la operaci├│n, no el significado.",
        explanation: "La media es equilibrio. La mediana es posici├│n.",
        exercise: "Crear dos conjuntos de datos con la misma media pero medianas distintas.",
        feedback: "┬┐Qu├® medida representa mejor al grupo ÔÇö y por qu├®?",
      },
      fle: {
        tag: "FLE / Franc├®s",
        problem: "Un vs Une",
        learnerSays: "Siempre los confundo.",
        diagnosis: "El g├®nero a├║n no se ve como sistema ÔÇö solo como reglas aleatorias.",
        explanation: "Agrupamos palabras por terminaciones, sonidos y patrones repetidos ÔÇö no por memorizaci├│n.",
        exercise: "Ordenar 20 sustantivos comunes. Luego explicar el patr├│n que notaste.",
        feedback: "┬┐Qu├® te ayud├│ a adivinar correctamente?",
      },
      steps: ["El alumno dice", "Diagn├│stico", "Explicaci├│n", "Ejercicio", "Feedback"],
    },
    qa: {
      title: "Preguntas que un reclutador podr├¡a hacerse",
      items: [
        { q: "┬┐Qu├® tipo de puesto buscas?", a: "Estoy abierto a un verdadero puesto de profesor, tutor├¡a, apoyo acad├®mico, FLE, formaci├│n o roles relacionados con la educaci├│n donde la claridad, la estructura y la adaptaci├│n importan." },
        { q: "┬┐Esto es solo tutor├¡a?", a: "No. La tutor├¡a es parte de mi experiencia, pero el objetivo es m├ís amplio: ense├▒ar, ayudar a los alumnos a progresar y contribuir a entornos educativos donde la explicaci├│n y la estructura importan." },
        { q: "┬┐Esto es principalmente sobre aplicaciones?", a: "No. La lecci├│n humana va primero. Las aplicaciones solo son ├║tiles cuando ayudan a diagnosticar, practicar, explicar o seguir el progreso." },
        { q: "┬┐Qu├® materias puedes ense├▒ar o apoyar?", a: "Matem├íticas, estad├¡stica, razonamiento cuantitativo, fundamentos de an├ílisis de datos, l├│gica de business analytics, metodolog├¡a y Franc├®s como Lengua Extranjera." },
        { q: "┬┐Qu├® hace diferente tu perfil?", a: "Combino experiencia docente, pensamiento anal├¡tico, cultura de datos, comunicaci├│n multiling├╝e y la capacidad de dise├▒ar herramientas de aprendizaje simples." },
        { q: "┬┐Est├ís disponible para entrevistas?", a: "S├¡. El mejor siguiente paso es una conversaci├│n directa." },
      ],
    },
    cta: {
      title: "Entrar en el aula",
      body: "Si buscas a alguien capaz de ense├▒ar con claridad, adaptarse a los alumnos y aportar estructura al aprendizaje, estar├® encantado de conversar.",
      button: "Contactar a Nathan",
      secondary: "Volver a NA Studio",
      email: "contact@nathanazoulay.com",
    },
    footer: {
      line: "NA Classroom ÔÇö un espacio pedag├│gico dedicado por Nathan Azoulay / NA Studio.",
      links: [
        { label: "NA Studio", href: "/" },
        { label: "NA Websites", href: "/" },
        { label: "Contacto", href: "mailto:contact@nathanazoulay.com" },
        { label: "LinkedIn", href: "https://linkedin.com" },
      ],
    },
  },
};

export default content;
