const content = {
  en: {
    nav: {
      profile: "Profile",
      principles: "Principles",
      tools: "Tools",
      lab: "Lesson Lab",
      qa: "Q&A",
      contact: "Contact",
      studio: "Back to NA Studio",
    },
    hero: {
      eyebrow: "NA Classroom / Teaching Portfolio",
      title: "Clarity first.\nConfidence follows.",
      subtitle: "A focused teaching portfolio by Nathan Azoulay — built around clear explanations, patient feedback, mathematics, FLE, and useful learning tools.",
      humanLine: "The best tool in the classroom is still attention.",
      cta1: "Enter the classroom",
      cta2: "See the method",
      annotations: ["why?", "almost", "try again", "clearer"],
    },
    desk: {
      title: "The teacher's desk",
      tagline: "Not technology instead of teaching. Technology after attention.",
      sheets: {
        profile: {
          label: "Profile",
          items: [
            { title: "Mathematics", detail: "Tutoring experience from fundamentals to exam-oriented reasoning." },
            { title: "Statistics", detail: "Comfortable explaining formulas through intuition, examples and interpretation." },
            { title: "Business Analytics", detail: "Academic path connecting quantitative reasoning, business context and decision-making." },
            { title: "Data analysis", detail: "Practical orientation toward cleaning, reporting, dashboards and operational insights." },
            { title: "Data science foundations", detail: "Enough ML culture to explain data logic without making it a technical showcase." },
            { title: "AI & digital culture", detail: "Uses digital tools as support for clarity and practice — never as a replacement for teaching." },
            { title: "Clear explanation", detail: "Focuses on making complex ideas usable, not impressive." },
          ],
        },
        experience: {
          label: "Experience",
          items: [
            { title: "Teaching & tutoring", detail: "Experience supporting learners through mathematics, methodology and academic progression." },
            { title: "Academic support", detail: "Helps students rebuild structure when a course feels fragmented or overwhelming." },
            { title: "Mathematics support", detail: "Works on both method and meaning: not only how to solve, but why the method works." },
            { title: "Statistics / quantitative reasoning", detail: "Connects calculations to interpretation — where many students lose confidence." },
            { title: "Methodology coaching", detail: "Helps learners organize revision, identify weak points and stop repeating mistakes." },
            { title: "Foreign learners", detail: "Experience helping non-native learners cross language and confidence barriers." },
            { title: "FLE / French as a Foreign Language", detail: "Supports French learning through patterns, examples, repetition and low-pressure correction." },
          ],
        },
        languages: {
          label: "Languages",
          items: [
            { title: "French — native", detail: "Native language, useful for precise explanation and FLE support." },
            { title: "English — B2 / professional", detail: "Comfortable enough to explain, exchange and support learners across languages." },
            { title: "Spanish — B1 / conversational", detail: "Useful for basic explanation bridges and multilingual learner contexts." },
          ],
          note: "Languages are not decoration here. They help Nathan explain the same idea through different cultural and linguistic entry points.",
        },
      },
    },
    board: {
      title: "What good teaching starts with",
      signature: "Teach the mistake, not just the lesson.",
      flow: "confusion → diagnosis → explanation → exercise → confidence",
      principles: [
        { num: "01", name: "Attention before explanation", note: "First observe: what is missing, what is confused, what is fragile." },
        { num: "02", name: "Clarity before speed", note: "Moving fast is useless if the learner is only copying steps." },
        { num: "03", name: "Feedback that can be used", note: "Correction shows what to do next, not only what went wrong." },
        { num: "04", name: "Confidence through structure", note: "Confidence grows when the learner sees a path, not a wall." },
        { num: "05", name: "Tools only when useful", note: "Digital tools support the lesson. They never replace the relationship." },
      ],
    },
    tools: {
      title: "Tools on the table",
      intro: "Digital tools are useful only when they help a teacher see better, explain better, or help a learner practice with less fear.",
      label: "Concepts / prototypes / educational explorations",
      statusLabel: "Status",
      githubLabel: "GitHub coming soon",
      closeLabel: "Close",
      apps: [
        {
          id: "formula-builder",
          name: "Formula Builder",
          short: "Understand formulas instead of memorizing them.",
          description: "Formula Builder deconstructs scientific and quantitative formulas step by step. The learner manipulates each part of the formula and sees what changes.",
          value: "Students often learn formulas like recipes. This tool helps them understand what each part means.",
          targets: ["Middle school", "High school", "Early university", "Statistics / data / finance beginners"],
          features: ["20 core formulas", "Interactive visualizations", "Mini exercises per formula", "Concrete real-world cases", "Teacher mode for custom sheets"],
          examples: ["Mean", "Percentage", "Speed = distance / time", "Probability", "Variance / std deviation", "Affine function", "Excel formulas"],
          status: "Concept",
          githubUrl: null,
        },
        {
          id: "error-diary",
          name: "Error Diary",
          short: "Turn recurring mistakes into targeted practice.",
          description: "A smart journal where the teacher records recurring mistakes and transforms them into exercises, patterns and structured feedback.",
          value: "Turns mistakes into usable feedback instead of repeated corrections.",
          targets: ["Any level", "High-stakes exam prep", "Learners stuck on the same errors"],
          features: ["Mistake categories", "Recurring pattern detection", "Exercise suggestions", "Student progress notes", "Teacher summary view"],
          examples: [],
          status: "Concept",
          githubUrl: null,
        },
        {
          id: "oralsafe",
          name: "OralSafe",
          short: "Practice speaking before feeling perfect.",
          description: "A low-pressure oral practice tool for shy learners and FLE learners. Built around short voice prompts, repetition and progressive confidence.",
          value: "Helps learners speak before they feel ready — which is when real acquisition begins.",
          targets: ["FLE learners", "Shy or anxious speakers", "B1-B2 oral prep"],
          features: ["Short voice prompts", "Repetition loops", "Confidence level tracking", "Pronunciation notes", "Teacher feedback mode"],
          examples: [],
          status: "Concept",
          githubUrl: null,
        },
        {
          id: "microexam",
          name: "MicroExam",
          short: "Check understanding in ten minutes.",
          description: "A mini-assessment generator for quick concept checks before moving forward. Reveals gaps early — not at the final exam.",
          value: "Most learners pass the lesson but fail the concept. MicroExam catches the gap.",
          targets: ["Any subject", "Before moving to a new chapter", "Revision sessions"],
          features: ["Topic selection", "10-minute test mode", "Auto-correction structure", "Teacher notes", "Revision suggestions"],
          examples: [],
          status: "Concept",
          githubUrl: null,
        },
        {
          id: "concept-builder",
          name: "Concept Builder",
          short: "Explain the same idea in several ways.",
          description: "A tool that helps teachers explain one concept through different modes: simple, visual, analogy-based, exam-focused or step-by-step.",
          value: "Every learner has a different entry point. Concept Builder finds theirs.",
          targets: ["Any teacher", "Learners who need alternative explanations", "Tutoring sessions"],
          features: ["Concept input", "Multiple explanation levels", "Analogy mode", "Exercise mode", "Teacher export"],
          examples: [],
          status: "Concept",
          githubUrl: null,
        },
        {
          id: "learning-map",
          name: "Learning Map",
          short: "See what is solid, fragile or missing.",
          description: "A visual map of learning progression. The teacher and learner see exactly what is mastered, what needs review, and what is blocking progress.",
          value: "Makes invisible gaps visible — before they become failures.",
          targets: ["Long-term tutoring", "Exam prep", "Teachers with multiple students"],
          features: ["Mastered / fragile / missing states", "Concept dependencies", "Progress path visualization", "Revision priorities", "Teacher & student views"],
          examples: [],
          status: "Concept",
          githubUrl: null,
        },
        {
          id: "fle-compass",
          name: "FLE Compass",
          short: "Turn learner answers into a clear teaching method.",
          description: "A structured FLE diagnostic for teachers and tutors: learner and parent questionnaires, teacher observation, pedagogical scoring and actionable reports — not an official certification, but a method for this person.",
          value: "Most FLE teachers know the level is uneven. FLE Compass maps confidence, blockages, motivation and priorities into a first-session plan.",
          targets: ["FLE teachers", "Private tutors", "Schools", "Child, teen and adult learners"],
          features: ["Multi-respondent sessions (learner, parent, teacher)", "Token-based shared links", "Pedagogical scoring engine", "Teacher / parent / learner reports", "PDF export"],
          examples: ["Express, standard and complete modes", "Reliability indicators", "Four-week plan suggestions"],
          status: "Live",
          githubUrl: "https://github.com/AzoulayNathan/FLECompass_FLEDiagnostic",
        },
      ],
    },
    lab: {
      titlePart1: "Two lessons",
      titlePart2: "Two ways",
      subtitle: "The same teaching attention, applied to two very different learner problems.",
      quote: {
        left: "Human first.",
        right: "Method next.",
        below: "Digital in support.",
      },
      math: {
        tag: "Mathematics",
        problem: "Mean vs Median",
        learnerSays: "I know the formula, but I don't know when to use it.",
        diagnosis: "The learner memorized the operation, not the meaning.",
        explanation: "Mean is balance. Median is position.",
        exercise: "Create two datasets with the same mean but different medians.",
        feedback: "Which measure represents the group better — and why?",
      },
      fle: {
        tag: "FLE / French",
        problem: "Un vs Une",
        learnerSays: "I always mix them up.",
        diagnosis: "Gender is not yet seen as a system — only as random rules.",
        explanation: "We group words by endings, sounds and repeated patterns — not by memorization.",
        exercise: "Sort 20 common nouns. Then explain the pattern you noticed.",
        feedback: "What helped you guess correctly?",
      },
      steps: ["Learner says", "Diagnosis", "Explanation", "Exercise", "Feedback"],
    },
    qa: {
      title: "Q&A",
      items: [
        {
          q: "What kind of position are you looking for?",
          a: "I am open to a real teaching position, tutoring, academic support, FLE, training, or education-adjacent roles where clarity, structure and adaptation matter.",
        },
        {
          q: "Is this only about tutoring?",
          a: "No. Tutoring is part of my experience, but the goal is broader: teaching, helping learners progress, and contributing to educational environments where explanation and structure matter.",
        },
        {
          q: "Is this mainly about apps?",
          a: "No. The human lesson comes first. Apps are only useful when they help diagnose, practice, explain or follow progress better.",
        },
        {
          q: "What subjects can you teach or support?",
          a: "Mathematics, statistics, quantitative reasoning, data analysis foundations, business analytics logic, methodology, and French as a Foreign Language.",
        },
        {
          q: "What makes your profile different?",
          a: "I combine teaching experience, analytical thinking, data culture, multilingual communication and the ability to design simple learning tools.",
        },
        {
          q: "Are you available for interviews?",
          a: "Yes. The best next step is a direct conversation.",
        },
      ],
    },
    contactPage: {
      eyebrow: "Contact",
      heading: "Let's start with a real conversation.",
      body: "For teaching opportunities, tutoring, FLE, or education-adjacent roles — I'm open to the right kind of message.",
      find: "Find me here",
      write: "Write to me",
      name: "Name",
      email: "Email",
      message: "Message",
      namePh: "Your name",
      emailPh: "Your email address",
      messagePh: "What would you like to discuss?",
      submit: "Start the conversation",
      sentH: "Message sent.",
      sentP: "I'll get back to you as soon as possible.",
      mailSubject: "Classroom contact",
    },
    cta: {
      title: "Enter the classroom",
      body: "If you are looking for someone who can teach clearly, adapt to learners, and bring structure into learning, I would be happy to talk.",
      button: "Contact Nathan",
      secondary: "Back to NA Studio",
      email: "contact@nathanazoulay.com",
    },
    footer: {
      line: "NA Classroom — a focused teaching room by Nathan Azoulay / NA Studio.",
      links: [
        { label: "NA Studio", href: "/" },
        { label: "NA Websites", href: "/" },
        { label: "Contact", href: "mailto:contact@nathanazoulay.com" },
        { label: "LinkedIn", href: "https://linkedin.com" },
      ],
    },
  },

  fr: {
    nav: {
      profile: "Profil",
      principles: "Principes",
      tools: "Outils",
      lab: "Labo",
      qa: "Q&R",
      contact: "Contact",
      studio: "Retour à NA Studio",
    },
    hero: {
      eyebrow: "NA Classroom / Portfolio pédagogique",
      title: "La clarté d'abord.\nLa confiance suit.",
      subtitle: "Un portfolio pédagogique ciblé par Nathan Azoulay — autour d'explications claires, de feedback patient, de mathématiques, de FLE et d'outils d'apprentissage utiles.",
      humanLine: "Le meilleur outil dans une salle de classe reste l'attention.",
      cta1: "Entrer dans la classe",
      cta2: "Voir la méthode",
      annotations: ["pourquoi ?", "presque", "réessaie", "plus clair"],
    },
    desk: {
      title: "Le bureau pédagogique",
      tagline: "Pas la technologie à la place de l'enseignement. La technologie après l'attention.",
      sheets: {
        profile: {
          label: "Profil",
          items: [
            { title: "Mathématiques", detail: "Expérience de tutorat des fondamentaux au raisonnement orienté examen." },
            { title: "Statistiques", detail: "À l'aise pour expliquer les formules par l'intuition, les exemples et l'interprétation." },
            { title: "Business Analytics", detail: "Parcours académique reliant raisonnement quantitatif, contexte métier et prise de décision." },
            { title: "Analyse de données", detail: "Orientation pratique vers le nettoyage, le reporting, les tableaux de bord et les insights opérationnels." },
            { title: "Fondations data science", detail: "Culture ML suffisante pour expliquer la logique des données sans en faire une vitrine technique." },
            { title: "Culture IA & numérique", detail: "Utilise les outils numériques comme support pour la clarté et la pratique — jamais à la place de l'enseignement." },
            { title: "Explication claire", detail: "Se concentre sur rendre les idées complexes utilisables, pas impressionnantes." },
          ],
        },
        experience: {
          label: "Expérience",
          items: [
            { title: "Enseignement et tutorat", detail: "Expérience d'accompagnement en mathématiques, méthodologie et progression académique." },
            { title: "Soutien scolaire", detail: "Aide les élèves à reconstruire la structure quand un cours semble fragmenté ou écrasant." },
            { title: "Soutien en mathématiques", detail: "Travaille sur méthode et sens : pas seulement comment résoudre, mais pourquoi la méthode fonctionne." },
            { title: "Statistiques / raisonnement quantitatif", detail: "Relie les calculs à l'interprétation — là où beaucoup d'étudiants perdent confiance." },
            { title: "Coaching méthodologique", detail: "Aide les apprenants à organiser la révision, identifier les points faibles et cesser de répéter les erreurs." },
            { title: "Apprenants étrangers", detail: "Expérience pour aider les non-natifs à franchir les barrières linguistiques et de confiance." },
            { title: "FLE / Français Langue Étrangère", detail: "Soutient l'apprentissage du français par les schémas, exemples, répétition et correction basse pression." },
          ],
        },
        languages: {
          label: "Langues",
          items: [
            { title: "Français — natif", detail: "Langue maternelle, utile pour une explication précise et le soutien FLE." },
            { title: "Anglais — B2 / professionnel", detail: "Assez à l'aise pour expliquer, échanger et accompagner les apprenants entre les langues." },
            { title: "Espagnol — B1 / conversationnel", detail: "Utile pour les ponts d'explication de base et les contextes d'apprenants multilingues." },
          ],
          note: "Les langues ne sont pas ici une décoration. Elles aident Nathan à expliquer la même idée à travers différents points d'entrée culturels et linguistiques.",
        },
      },
    },
    board: {
      title: "Ce par quoi commence un bon enseignement",
      signature: "Enseigner l'erreur, pas seulement la leçon.",
      flow: "confusion → diagnostic → explication → exercice → confiance",
      principles: [
        { num: "01", name: "L'attention avant l'explication", note: "Observer d'abord : ce qui manque, ce qui est confus, ce qui est fragile." },
        { num: "02", name: "La clarté avant la vitesse", note: "Aller vite ne sert à rien si l'élève ne fait que copier des étapes." },
        { num: "03", name: "Un feedback utilisable", note: "La correction montre quoi faire ensuite, pas seulement ce qui est faux." },
        { num: "04", name: "La confiance par la structure", note: "La confiance grandit quand l'élève voit un chemin, pas un mur." },
        { num: "05", name: "Les outils seulement quand utiles", note: "Les outils numériques soutiennent le cours. Ils ne remplacent jamais la relation." },
      ],
    },
    tools: {
      title: "Des outils sur la table",
      intro: "Les outils numériques sont utiles seulement quand ils aident un enseignant à mieux voir, mieux expliquer, ou un apprenant à pratiquer avec moins de peur.",
      label: "Concepts / prototypes / explorations pédagogiques",
      statusLabel: "Statut",
      githubLabel: "GitHub bientôt",
      closeLabel: "Fermer",
      apps: [
        {
          id: "formula-builder",
          name: "Formula Builder",
          short: "Comprendre les formules au lieu de les mémoriser.",
          description: "Formula Builder déconstruit les formules scientifiques et quantitatives étape par étape. L'apprenant manipule chaque partie et voit ce qui change.",
          value: "Les élèves apprennent souvent les formules comme des recettes. Cet outil les aide à comprendre ce que chaque partie signifie.",
          targets: ["Collège", "Lycée", "Début universitaire", "Débutants en stats / data / finance"],
          features: ["20 formules essentielles", "Visualisations interactives", "Mini exercices par formule", "Cas concrets", "Mode enseignant"],
          examples: ["Moyenne", "Pourcentage", "Vitesse = distance / temps", "Probabilité", "Variance / écart-type", "Fonction affine", "Formules Excel"],
          status: "Concept",
          githubUrl: null,
        },
        {
          id: "error-diary",
          name: "Error Diary",
          short: "Transformer les erreurs récurrentes en exercices ciblés.",
          description: "Un journal intelligent où l'enseignant consigne les erreurs récurrentes et les transforme en exercices, schémas et feedback structuré.",
          value: "Transforme les erreurs en feedback utilisable plutôt qu'en corrections répétées.",
          targets: ["Tous niveaux", "Préparation aux examens", "Apprenants bloqués sur les mêmes erreurs"],
          features: ["Catégories d'erreurs", "Détection de schémas récurrents", "Suggestions d'exercices", "Notes de progression", "Vue synthétique enseignant"],
          examples: [],
          status: "Concept",
          githubUrl: null,
        },
        {
          id: "oralsafe",
          name: "OralSafe",
          short: "Pratiquer l'oral avant de se sentir parfait.",
          description: "Un outil de pratique orale basse pression pour les apprenants timides et les apprenants en FLE. Basé sur des prompts courts, la répétition et la confiance progressive.",
          value: "Aide les apprenants à parler avant de se sentir prêts — moment où commence vraiment l'acquisition.",
          targets: ["Apprenants FLE", "Locuteurs timides ou anxieux", "Préparation orale B1-B2"],
          features: ["Prompts vocaux courts", "Boucles de répétition", "Suivi du niveau de confiance", "Notes de prononciation", "Mode feedback enseignant"],
          examples: [],
          status: "Concept",
          githubUrl: null,
        },
        {
          id: "microexam",
          name: "MicroExam",
          short: "Vérifier la compréhension en dix minutes.",
          description: "Un générateur de mini-évaluations pour vérifier rapidement qu'un concept est compris avant d'avancer.",
          value: "La plupart des apprenants passent la leçon mais ratent le concept. MicroExam comble cet écart.",
          targets: ["Toute matière", "Avant de passer au chapitre suivant", "Sessions de révision"],
          features: ["Sélection de thème", "Mode test 10 minutes", "Structure de correction automatique", "Notes enseignant", "Suggestions de révision"],
          examples: [],
          status: "Concept",
          githubUrl: null,
        },
        {
          id: "concept-builder",
          name: "Concept Builder",
          short: "Expliquer la même idée de plusieurs façons.",
          description: "Un outil qui aide les enseignants à expliquer un concept selon différents modes : simple, visuel, par analogie, orienté examen ou étape par étape.",
          value: "Chaque apprenant a un point d'entrée différent. Concept Builder le trouve.",
          targets: ["Tout enseignant", "Apprenants nécessitant des explications alternatives", "Sessions de tutorat"],
          features: ["Saisie du concept", "Plusieurs niveaux d'explication", "Mode analogie", "Mode exercice", "Export enseignant"],
          examples: [],
          status: "Concept",
          githubUrl: null,
        },
        {
          id: "learning-map",
          name: "Learning Map",
          short: "Voir ce qui est solide, fragile ou manquant.",
          description: "Une carte visuelle de la progression d'apprentissage. L'enseignant et l'apprenant voient précisément ce qui est maîtrisé, ce qui doit être revu et ce qui bloque.",
          value: "Rend les lacunes invisibles visibles — avant qu'elles deviennent des échecs.",
          targets: ["Tutorat long terme", "Préparation aux examens", "Enseignants avec plusieurs élèves"],
          features: ["États maîtrisé / fragile / manquant", "Dépendances entre concepts", "Visualisation du chemin", "Priorités de révision", "Vues enseignant et élève"],
          examples: [],
          status: "Concept",
          githubUrl: null,
        },
        {
          id: "fle-compass",
          name: "FLE Compass",
          short: "Transformer les réponses en méthode d'enseignement claire.",
          description: "Un diagnostic FLE structuré pour professeurs et tuteurs : questionnaires apprenant et parent, observation professeur, scoring pédagogique et rapports actionnables — une estimation pédagogique, pas une certification officielle.",
          value: "Beaucoup de profs FLE savent que le niveau est inégal. FLE Compass cartographie confiance, blocages, motivation et priorités en plan de première séance.",
          targets: ["Professeurs FLE", "Tuteurs privés", "Écoles", "Apprenants enfants, ados et adultes"],
          features: ["Sessions multi-répondants (apprenant, parent, prof)", "Liens partagés par token", "Moteur de scoring pédagogique", "Rapports prof / parent / apprenant", "Export PDF"],
          examples: ["Modes express, standard et complet", "Indicateurs de fiabilité", "Suggestions de plan sur 4 semaines"],
          status: "Live",
          githubUrl: "https://github.com/AzoulayNathan/FLECompass_FLEDiagnostic",
        },
      ],
    },
    lab: {
      titlePart1: "Deux leçons",
      titlePart2: "Deux chemins",
      subtitle: "La même attention pédagogique, appliquée à deux problèmes d'apprentissage très différents.",
      quote: {
        left: "L'humain d'abord.",
        right: "La méthode ensuite.",
        below: "Le digital en soutien.",
      },
      math: {
        tag: "Mathématiques",
        problem: "Moyenne vs Médiane",
        learnerSays: "Je connais la formule, mais je ne sais pas quand l'utiliser.",
        diagnosis: "L'élève a mémorisé l'opération, pas le sens.",
        explanation: "La moyenne, c'est l'équilibre. La médiane, c'est la position.",
        exercise: "Créer deux jeux de données avec la même moyenne mais des médianes différentes.",
        feedback: "Quelle mesure représente mieux le groupe — et pourquoi ?",
      },
      fle: {
        tag: "FLE / Français",
        problem: "Un vs Une",
        learnerSays: "Je les mélange toujours.",
        diagnosis: "Le genre n'est pas encore perçu comme un système — seulement comme des règles aléatoires.",
        explanation: "On regroupe les mots par terminaisons, sons et schémas répétés — pas par mémorisation.",
        exercise: "Trier 20 noms courants. Puis expliquer le schéma remarqué.",
        feedback: "Qu'est-ce qui vous a aidé à deviner correctement ?",
      },
      steps: ["L'élève dit", "Diagnostic", "Explication", "Exercice", "Feedback"],
    },
    qa: {
      title: "Q&A",
      items: [
        { q: "Quel type de poste recherchez-vous ?", a: "Je suis ouvert à un vrai poste d'enseignant, au tutorat, au soutien scolaire, au FLE, à la formation ou à des rôles liés à l'éducation où la clarté, la structure et l'adaptation comptent." },
        { q: "Est-ce seulement du tutorat ?", a: "Non. Le tutorat fait partie de mon expérience, mais l'objectif est plus large : enseigner, aider les apprenants à progresser et contribuer à des environnements éducatifs où l'explication et la structure comptent." },
        { q: "Est-ce principalement une question d'applications ?", a: "Non. La leçon humaine vient d'abord. Les applications ne sont utiles que si elles aident à diagnostiquer, pratiquer, expliquer ou suivre les progrès." },
        { q: "Quelles matières pouvez-vous enseigner ou accompagner ?", a: "Mathématiques, statistiques, raisonnement quantitatif, bases d'analyse de données, logique business analytics, méthodologie et Français Langue Étrangère." },
        { q: "Qu'est-ce qui rend votre profil différent ?", a: "Je combine expérience pédagogique, pensée analytique, culture data, communication multilingue et capacité à concevoir des outils d'apprentissage simples." },
        { q: "Êtes-vous disponible pour un entretien ?", a: "Oui. La meilleure prochaine étape est une conversation directe." },
      ],
    },
    contactPage: {
      eyebrow: "Contact",
      heading: "Commençons par une vraie conversation.",
      body: "Pour un poste d'enseignement, du tutorat, du FLE ou un rôle proche de l'éducation — je suis ouvert au bon type de message.",
      find: "Me retrouver ici",
      write: "M'écrire",
      name: "Nom",
      email: "Email",
      message: "Message",
      namePh: "Votre nom",
      emailPh: "Votre adresse email",
      messagePh: "De quoi souhaitez-vous parler ?",
      submit: "Démarrer la conversation",
      sentH: "Message envoyé.",
      sentP: "Je reviendrai vers vous dès que possible.",
      mailSubject: "Contact Classroom",
    },
    cta: {
      title: "Entrer dans la classe",
      body: "Si vous cherchez quelqu'un capable d'enseigner clairement, de s'adapter aux apprenants et d'apporter de la structure dans l'apprentissage, je serais heureux d'échanger.",
      button: "Contacter Nathan",
      secondary: "Retour à NA Studio",
      email: "contact@nathanazoulay.com",
    },
    footer: {
      line: "NA Classroom — un espace pédagogique dédié par Nathan Azoulay / NA Studio.",
      links: [
        { label: "NA Studio", href: "/" },
        { label: "NA Websites", href: "/" },
        { label: "Contact", href: "mailto:contact@nathanazoulay.com" },
        { label: "LinkedIn", href: "https://linkedin.com" },
      ],
    },
  },

  es: {
    nav: {
      profile: "Perfil",
      principles: "Principios",
      tools: "Herramientas",
      lab: "Laboratorio",
      qa: "Preguntas",
      contact: "Contacto",
      studio: "Volver a NA Studio",
    },
    hero: {
      eyebrow: "NA Classroom / Portfolio pedagógico",
      title: "Primero claridad.\nLuego confianza.",
      subtitle: "Un portfolio pedagógico enfocado por Nathan Azoulay — basado en explicaciones claras, feedback paciente, matemáticas, FLE y herramientas de aprendizaje útiles.",
      humanLine: "La mejor herramienta en el aula sigue siendo la atención.",
      cta1: "Entrar en el aula",
      cta2: "Ver el método",
      annotations: ["¿por qué?", "casi", "inténtalo", "más claro"],
    },
    desk: {
      title: "El escritorio pedagógico",
      tagline: "No tecnología en lugar de enseñanza. Tecnología después de la atención.",
      sheets: {
        profile: {
          label: "Perfil",
          items: [
            { title: "Matemáticas", detail: "Experiencia de tutoría desde los fundamentos hasta el razonamiento orientado a exámenes." },
            { title: "Estadística", detail: "Cómodo explicando fórmulas a través de la intuición, ejemplos e interpretación." },
            { title: "Business Analytics", detail: "Trayectoria académica que conecta razonamiento cuantitativo, contexto empresarial y toma de decisiones." },
            { title: "Análisis de datos", detail: "Orientación práctica hacia limpieza, reporting, dashboards e insights operacionales." },
            { title: "Fundamentos data science", detail: "Cultura ML suficiente para explicar la lógica de datos sin convertirlo en un escaparate técnico." },
            { title: "Cultura IA & digital", detail: "Usa herramientas digitales como apoyo para la claridad y la práctica — nunca en lugar de la enseñanza." },
            { title: "Explicación clara", detail: "Se centra en hacer las ideas complejas utilizables, no impresionantes." },
          ],
        },
        experience: {
          label: "Experiencia",
          items: [
            { title: "Enseñanza y tutoría", detail: "Experiencia apoyando alumnos en matemáticas, metodología y progresión académica." },
            { title: "Apoyo académico", detail: "Ayuda a los alumnos a reconstruir la estructura cuando un curso se siente fragmentado o abrumador." },
            { title: "Apoyo en matemáticas", detail: "Trabaja en método y significado: no solo cómo resolver, sino por qué funciona el método." },
            { title: "Estadística / razonamiento cuantitativo", detail: "Conecta cálculos con interpretación — donde muchos alumnos pierden confianza." },
            { title: "Coaching metodológico", detail: "Ayuda a los alumnos a organizar la revisión, identificar puntos débiles y dejar de repetir errores." },
            { title: "Alumnos extranjeros", detail: "Experiencia ayudando a no nativos a cruzar barreras lingüísticas y de confianza." },
            { title: "FLE / Francés como Lengua Extranjera", detail: "Apoya el aprendizaje del francés mediante patrones, ejemplos, repetición y corrección sin presión." },
          ],
        },
        languages: {
          label: "Idiomas",
          items: [
            { title: "Francés — nativo", detail: "Lengua materna, útil para explicación precisa y apoyo FLE." },
            { title: "Inglés — B2 / profesional", detail: "Lo suficientemente cómodo para explicar, intercambiar y apoyar alumnos entre idiomas." },
            { title: "Español — B1 / conversacional", detail: "Ütil para puentes básicos de explicación y contextos de alumnos multilingües." },
          ],
          note: "Los idiomas no son decoración aquí. Ayudan a Nathan a explicar la misma idea a través de diferentes puntos de entrada culturales y lingüísticos.",
        },
      },
    },
    board: {
      title: "Por dónde empieza una buena enseñanza",
      signature: "Enseña el error, no solo la lección.",
      flow: "confusión → diagnóstico → explicación → ejercicio → confianza",
      principles: [
        { num: "01", name: "Atención antes que explicación", note: "Primero observar: qué falta, qué está confuso, qué es frágil." },
        { num: "02", name: "Claridad antes que velocidad", note: "Ir rápido no sirve si el alumno solo copia pasos." },
        { num: "03", name: "Feedback que se pueda usar", note: "La corrección muestra qué hacer después, no solo qué salió mal." },
        { num: "04", name: "Confianza a través de la estructura", note: "La confianza crece cuando el alumno ve un camino, no un muro." },
        { num: "05", name: "Herramientas solo cuando son útiles", note: "Las herramientas digitales apoyan la clase. Nunca reemplazan la relación." },
      ],
    },
    tools: {
      title: "Herramientas sobre la mesa",
      intro: "Las herramientas digitales solo son útiles cuando ayudan al profesor a ver mejor, explicar mejor o al alumno a practicar con menos miedo.",
      label: "Conceptos / prototipos / exploraciones educativas",
      statusLabel: "Estado",
      githubLabel: "GitHub próximamente",
      closeLabel: "Cerrar",
      apps: [
        {
          id: "formula-builder",
          name: "Formula Builder",
          short: "Entender las fórmulas en lugar de memorizarlas.",
          description: "Formula Builder deconstruye fórmulas científicas y cuantitativas paso a paso. El alumno manipula cada parte y ve qué cambia.",
          value: "Los alumnos suelen aprender fórmulas como recetas. Esta herramienta les ayuda a entender qué significa cada parte.",
          targets: ["Secundaria", "Bachillerato", "Inicio universitario", "Principiantes en estadística / datos / finanzas"],
          features: ["20 fórmulas esenciales", "Visualizaciones interactivas", "Mini ejercicios por fórmula", "Casos reales", "Modo profesor"],
          examples: ["Media", "Porcentaje", "Velocidad = distancia / tiempo", "Probabilidad", "Varianza / desviación estándar", "Función afín", "Fórmulas Excel"],
          status: "Concepto",
          githubUrl: null,
        },
        {
          id: "error-diary",
          name: "Error Diary",
          short: "Convertir errores recurrentes en práctica dirigida.",
          description: "Un diario inteligente donde el profesor registra errores recurrentes y los transforma en ejercicios, patrones y feedback estructurado.",
          value: "Convierte errores en feedback útil en lugar de correcciones repetidas.",
          targets: ["Cualquier nivel", "Preparación a exámenes", "Alumnos atascados en los mismos errores"],
          features: ["Categorías de errores", "Detección de patrones recurrentes", "Sugerencias de ejercicios", "Notas de progreso", "Vista resumen profesor"],
          examples: [],
          status: "Concepto",
          githubUrl: null,
        },
        {
          id: "oralsafe",
          name: "OralSafe",
          short: "Practicar el oral antes de sentirse perfecto.",
          description: "Una herramienta de práctica oral sin presión para alumnos tímidos y de FLE. Basada en prompts cortos, repetición y confianza progresiva.",
          value: "Ayuda a los alumnos a hablar antes de sentirse listos — cuando comienza la adquisición real.",
          targets: ["Alumnos de FLE", "Hablantes tímidos o ansiosos", "Preparación oral B1-B2"],
          features: ["Prompts de voz cortos", "Bucles de repetición", "Seguimiento del nivel de confianza", "Notas de pronunciación", "Modo feedback profesor"],
          examples: [],
          status: "Concepto",
          githubUrl: null,
        },
        {
          id: "microexam",
          name: "MicroExam",
          short: "Comprobar la comprensión en diez minutos.",
          description: "Un generador de mini-evaluaciones para verificar rápidamente que un concepto se entendió antes de avanzar.",
          value: "La mayoría de alumnos pasan la clase pero fallan el concepto. MicroExam detecta ese hueco.",
          targets: ["Cualquier materia", "Antes de pasar al siguiente tema", "Sesiones de repaso"],
          features: ["Selección de tema", "Modo test 10 minutos", "Estructura de corrección automática", "Notas del profesor", "Sugerencias de revisión"],
          examples: [],
          status: "Concepto",
          githubUrl: null,
        },
        {
          id: "concept-builder",
          name: "Concept Builder",
          short: "Explicar la misma idea de varias maneras.",
          description: "Una herramienta que ayuda a los profesores a explicar un concepto mediante distintos modos: simple, visual, por analogía, orientado a examen o paso a paso.",
          value: "Cada alumno tiene un punto de entrada diferente. Concept Builder lo encuentra.",
          targets: ["Cualquier profesor", "Alumnos que necesitan explicaciones alternativas", "Sesiones de tutoría"],
          features: ["Entrada del concepto", "Varios niveles de explicación", "Modo analogía", "Modo ejercicio", "Exportación para profesor"],
          examples: [],
          status: "Concepto",
          githubUrl: null,
        },
        {
          id: "learning-map",
          name: "Learning Map",
          short: "Ver lo que es sólido, frágil o falta.",
          description: "Un mapa visual de la progresión de aprendizaje. El profesor y el alumno ven exactamente qué está dominado, qué hay que revisar y qué bloquea el avance.",
          value: "Hace visibles las lagunas invisibles — antes de que se conviertan en fracasos.",
          targets: ["Tutoría a largo plazo", "Preparación a exámenes", "Profesores con varios alumnos"],
          features: ["Estados dominado / frágil / faltante", "Dependencias entre conceptos", "Visualización del camino", "Prioridades de revisión", "Vistas profesor y alumno"],
          examples: [],
          status: "Concepto",
          githubUrl: null,
        },
        {
          id: "fle-compass",
          name: "FLE Compass",
          short: "Convertir las respuestas en un método de enseñanza claro.",
          description: "Un diagnóstico FLE estructurado para profesores y tutores: cuestionarios del alumno y del padre, observación del profesor, puntuación pedagógica e informes accionables — una estimación pedagógica, no una certificación oficial.",
          value: "Muchos profesores de FLE saben que el nivel es desigual. FLE Compass mapea confianza, bloqueos, motivación y prioridades en un plan para la primera sesión.",
          targets: ["Profesores de FLE", "Tutores privados", "Escuelas", "Alumnos niños, adolescentes y adultos"],
          features: ["Sesiones multi-respondiente (alumno, padre, prof)", "Enlaces compartidos por token", "Motor de puntuación pedagógica", "Informes prof / padre / alumno", "Exportación PDF"],
          examples: ["Modos express, standard y complete", "Indicadores de fiabilidad", "Sugerencias de plan a 4 semanas"],
          status: "Live",
          githubUrl: "https://github.com/AzoulayNathan/FLECompass_FLEDiagnostic",
        },
      ],
    },
    lab: {
      titlePart1: "Dos lecciones",
      titlePart2: "Dos caminos",
      subtitle: "La misma atención pedagógica, aplicada a dos problemas de aprendizaje muy distintos.",
      quote: {
        left: "Lo humano primero.",
        right: "El método después.",
        below: "Lo digital en apoyo.",
      },
      math: {
        tag: "Matemáticas",
        problem: "Media vs Mediana",
        learnerSays: "Conozco la fórmula, pero no sé cuándo usarla.",
        diagnosis: "El alumno memorizó la operación, no el significado.",
        explanation: "La media es equilibrio. La mediana es posición.",
        exercise: "Crear dos conjuntos de datos con la misma media pero medianas distintas.",
        feedback: "¿Qué medida representa mejor al grupo — y por qué?",
      },
      fle: {
        tag: "FLE / Francés",
        problem: "Un vs Une",
        learnerSays: "Siempre los confundo.",
        diagnosis: "El género aún no se ve como sistema — solo como reglas aleatorias.",
        explanation: "Agrupamos palabras por terminaciones, sonidos y patrones repetidos — no por memorización.",
        exercise: "Ordenar 20 sustantivos comunes. Luego explicar el patrón que notaste.",
        feedback: "¿Qué te ayudó a adivinar correctamente?",
      },
      steps: ["El alumno dice", "Diagnóstico", "Explicación", "Ejercicio", "Feedback"],
    },
    qa: {
      title: "Q&A",
      items: [
        { q: "¿Qué tipo de puesto buscas?", a: "Estoy abierto a un verdadero puesto de profesor, tutoría, apoyo académico, FLE, formación o roles relacionados con la educación donde la claridad, la estructura y la adaptación importan." },
        { q: "¿Esto es solo tutoría?", a: "No. La tutoría es parte de mi experiencia, pero el objetivo es más amplio: enseñar, ayudar a los alumnos a progresar y contribuir a entornos educativos donde la explicación y la estructura importan." },
        { q: "¿Esto es principalmente sobre aplicaciones?", a: "No. La lección humana va primero. Las aplicaciones solo son útiles cuando ayudan a diagnosticar, practicar, explicar o seguir el progreso." },
        { q: "¿Qué materias puedes enseñar o apoyar?", a: "Matemáticas, estadística, razonamiento cuantitativo, fundamentos de análisis de datos, lógica de business analytics, metodología y Francés como Lengua Extranjera." },
        { q: "¿Qué hace diferente tu perfil?", a: "Combino experiencia docente, pensamiento analítico, cultura de datos, comunicación multilingüe y la capacidad de diseñar herramientas de aprendizaje simples." },
        { q: "¿Estás disponible para entrevistas?", a: "Sí. El mejor siguiente paso es una conversación directa." },
      ],
    },
    contactPage: {
      eyebrow: "Contacto",
      heading: "Empecemos por una conversación real.",
      body: "Para oportunidades de enseñanza, tutoría, FLE o roles cercanos a la educación — estoy abierto al tipo de mensaje adecuado.",
      find: "Encuéntrame aquí",
      write: "Escríbeme",
      name: "Nombre",
      email: "Correo",
      message: "Mensaje",
      namePh: "Tu nombre",
      emailPh: "Tu correo electrónico",
      messagePh: "¿De qué te gustaría hablar?",
      submit: "Iniciar la conversación",
      sentH: "Mensaje enviado.",
      sentP: "Te responderé lo antes posible.",
      mailSubject: "Contacto Classroom",
    },
    cta: {
      title: "Entrar en el aula",
      body: "Si buscas a alguien capaz de enseñar con claridad, adaptarse a los alumnos y aportar estructura al aprendizaje, estaré encantado de conversar.",
      button: "Contactar a Nathan",
      secondary: "Volver a NA Studio",
      email: "contact@nathanazoulay.com",
    },
    footer: {
      line: "NA Classroom — un espacio pedagógico dedicado por Nathan Azoulay / NA Studio.",
      links: [
        { label: "NA Studio", href: "/" },
        { label: "NA Websites", href: "/" },
        { label: "Contacto", href: "mailto:contact@nathanazoulay.com" },
        { label: "LinkedIn", href: "https://linkedin.com" },
      ],
    },
  },
};

export default content;
